spring.application.name=dev
spring.main.web-application-type=none
spring.shell.interactive.enabled=true

logging.file.name= shell.log

aws.accessKeyId=AKIA2RPUKVMZYCZKD2GV
aws.secretAccessKey=
aws.region=ap-south-1
aws.s3.bucket-name=resparo-backup-bucket
